### PR TITLE
General update (App, Runtime & dependencies)

### PR DESCRIPTION
**Pull request by travier**
- Switch to 5.15-21.08 KDE Runtime
- Update to 5.6.2
- Update dependencies
- Remove now unneeded patches

### CODE REVIEW

**Comment by tsdgeos** [comment]
bot, build

**Comment by travier** [comment]
I'm going to update everything for this one as a lot of deps needs an update.

**Comment by travier** [comment]
bot, build

**Comment by travier** [comment]
Failed on download issues. aarch64 build successful.
bot, build

**Pull request merged**
